Persistent, Inpersistent(temporary) holograms
FancyMcPlugins/FancyHolograms pull request #96
Opened 2024-05-21 09:52 UTC by UsainSrht

2024-05-21 10:37 UTC, OakLoaf requested changes
This looks really good, would be a helpful feature too!

2024-05-21 10:37 UTC, OakLoaf commented on src/main/java/de/oliver/fancyholograms/HologramManagerImpl.java
> +
I think I would personally name this `getPersistentHolograms` and then revert `getAllHolograms` to `getHolograms`.

2024-05-21 14:25 UTC, OakLoaf commented
Just thought I'd prompt this thought that I just had - would `HologramManagerImpl#reloadHolograms` cause all non-persistent holograms to be deleted on plugin reload?

2024-05-21 14:28 UTC, UsainSrht commented
> Just thought I'd prompt this thought that I just had - would `HologramManagerImpl#reloadHolograms` cause all non-persistent holograms to be deleted on plugin reload?

probably, let me test and resolve it if thats the case

2024-05-21 18:06 UTC, OakLoaf commented
This PR will resolve #50

2024-05-23 08:00 UTC, OakLoaf commented on src/main/java/de/oliver/fancyholograms/HologramManagerImpl.java
> +
Awesome, I think the only thing left would be to look at those methods names mentioned above

2024-05-23 08:00 UTC, OakLoaf commented
Awesome, I think the only thing left would be to look at those methods names mentioned above

2024-05-23 08:08 UTC, OakLoaf approved these changes
This looks good to me!

2024-06-01 13:59 UTC, merged